name: aioft_bpo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_phone_direct_caller: ^2.1.0
  flutter_animated_dialog: ^2.0.1
  mobile_number: ^1.0.4
  awesome_dialog: ^2.1.1
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.11
  introduction_screen: ^2.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono.ttf
    - family: RobotoMono-bold
      fonts:
        - asset: fonts/RobotoMono-bold.ttf
